# Generated by Django 5.2.4 on 2025-07-30 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ROIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('quick', 'Quick Estimate'), ('full', 'Full Calculator')], max_length=32)),
                ('annual_revenue', models.BigIntegerField()),
                ('gross_margin', models.FloatField()),
                ('container_app_fraction', models.FloatField()),
                ('annual_cloud_spend', models.BigIntegerField()),
                ('compute_spend_fraction', models.FloatField()),
                ('cost_sensitive_fraction', models.FloatField()),
                ('num_engineers', models.IntegerField()),
                ('engineer_cost_per_year', models.BigIntegerField()),
                ('ops_time_fraction', models.FloatField()),
                ('ops_toil_fraction', models.FloatField()),
                ('toil_reduction_fraction', models.FloatField(blank=True, null=True)),
                ('avg_response_time_sec', models.FloatField(blank=True, null=True)),
                ('exec_time_influence_fraction', models.FloatField(blank=True, null=True)),
                ('lat_red_container', models.FloatField(blank=True, null=True)),
                ('lat_red_serverless', models.FloatField(blank=True, null=True)),
                ('revenue_lift_per_100ms', models.FloatField(blank=True, null=True)),
                ('current_fci_fraction', models.FloatField(blank=True, null=True)),
                ('fci_reduction_fraction', models.FloatField(blank=True, null=True)),
                ('cost_per_1pct_fci', models.FloatField(blank=True, null=True)),
                ('cloud_savings', models.FloatField()),
                ('productivity_gain', models.FloatField()),
                ('performance_gain', models.FloatField()),
                ('availability_gain', models.FloatField()),
                ('total_annual_gain', models.FloatField()),
                ('roi_percent', models.FloatField()),
                ('payback_months', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
