# Generated by Django 5.2.5 on 2025-09-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_roiresult_payment_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercalculationlimit',
            name='unlimited_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercalculationlimit',
            name='unlimited_access_purchased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
