"""
Django settings for roi_calculator project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


import os
from pathlib import Path

# Load environment variables from .env file (optional)
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    # dotenv not available, continue without it
    pass

# Load decouple for config (optional)
try:
    from decouple import config
except ImportError:
    # decouple not available, use os.getenv instead
    def config(key, default=None):
        return os.getenv(key, default)

# Load API keys from config file (optional)
try:
    from config import (
        GEMINI_API_KEY as CONFIG_GEMINI_KEY,
        RAZORPAY_KEY_ID as CONFIG_RAZORPAY_KEY_ID,
        RAZORPAY_KEY_SECRET as CONFIG_RAZORPAY_KEY_SECRET,
        RAZORPAY_PAYMENT_BUTTON_ID as CONFIG_RAZORPAY_PAYMENT_BUTTON_ID
    )
    
    # Set environment variables from config if they exist and are not placeholders
    if CONFIG_GEMINI_KEY and CONFIG_GEMINI_KEY != "your-gemini-api-key-here":
        os.environ['GEMINI_API_KEY'] = CONFIG_GEMINI_KEY
    
    if CONFIG_RAZORPAY_KEY_ID and CONFIG_RAZORPAY_KEY_ID != "rzp_test_your_key_id_here":
        os.environ['RAZORPAY_KEY_ID'] = CONFIG_RAZORPAY_KEY_ID
    
    if CONFIG_RAZORPAY_KEY_SECRET and CONFIG_RAZORPAY_KEY_SECRET != "your_razorpay_secret_here":
        os.environ['RAZORPAY_KEY_SECRET'] = CONFIG_RAZORPAY_KEY_SECRET
    
    if CONFIG_RAZORPAY_PAYMENT_BUTTON_ID:
        os.environ['RAZORPAY_PAYMENT_BUTTON_ID'] = CONFIG_RAZORPAY_PAYMENT_BUTTON_ID
        
except ImportError:
    # config.py not available, continue without it
    print("Info: config.py not found. Using environment variables or defaults.")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-your-secret-key-here-change-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'testserver']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'calculator',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'roi_calculator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'roi_calculator.wsgi.application'

# Database - Using SQLite3 (Django default)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Session settings
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Google Gemini API Configuration
# Get the key (optional - won't crash if not found)
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# Optional: check if loaded correctly (only warn, don't crash)
if not GEMINI_API_KEY:
    print("Warning: GEMINI_API_KEY not found in environment. Chatbot features may not work.")


# Razorpay Configuration
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID', 'rzp_test_your_key_id_here')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET', 'your_razorpay_secret_here')
RAZORPAY_PAYMENT_BUTTON_ID = os.getenv('RAZORPAY_PAYMENT_BUTTON_ID', 'pl_RDhRAQjOTNv1Jm')
